name: Pytest and Coverage

permissions:
  contents: read

on:
  pull_request:
  push: 
    branches:
      - master

jobs:
  pytest:
    name: Pytest and Coverage
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'  # or match your `.python-version`

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6
        with:
          activate-environment: true
      
      - name: Create and populate virtualenv
        run: |
          uv pip install -r requirements.txt

      - name: Run pytest
        run: PYTHONPATH=. uv run coverage run -m pytest
      
      - name: Run coverage
        run: PYTHONPATH=. uv run coverage report -m --fail-under=100
