# This workflow will upload the package to PyPi when a release is created
# It uses the trusted publisher authentication model, no more secrets and api keys

name: Upload Python Package

on: workflow_dispatch

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    permissions:
      # IMPORTANT: this permission is mandatory for Trusted Publishing
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build package
      run: python -m build
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/